image: containers.cognigencorp.com/r/361:latest

pages:
  script:
    - bash -lc "v=`sed -n \"s/Version:\s*\([^ ]*\)/\1/p\" DESCRIPTION`; sed -i \"s/\$version\$/'$v'/g\" vignettes/intro.Rmd; Rscript -e 'install.packages(\"pkgdown\"); pkgdown::build_site()'"
  artifacts:
    paths:
      - public
  only:
    - master
